### ISSUE TITLE
Forgot Mekanism

### ISSUE THREAD

**Issue by Items3Sacred** [ripley2459/new-elysium#1]
> Main mods:
>
> Tinker's Construct;
> Industrial Foregoing;
> Nuclearcraft;
> **Mekanism**;
> Advanced Rocketry;
> Techguns;
> RF Tools;
> Applied Energetics;
> Draconic Evolution;
> Project E. 

**No** Mekanism in Pack

**Comment by ripley2459** [comment]
The version of the pack with the correct mods list under review.
